server:
  port: 9801

spring:
  application:
    name: server01-service
  profiles:
    active: dev
  config:
    import: 
      - "optional:nacos:server01-config.yml"
      - "optional:nacos:common-config.yml"
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:18848
        namespace: public
        group: DEFAULT_GROUP
        file-extension: yml
        refresh-enabled: true
        shared-configs:
          - data-id: common-config.yml
            group: DEFAULT_GROUP
            refresh: true
        extension-configs:
          - data-id: server01-config.yml
            group: DEFAULT_GROUP
            refresh: true
      discovery:
        server-addr: 127.0.0.1:18848
        namespace: public
        group: DEFAULT_GROUP

# 暴露配置刷新端点
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info