server:
  port: 9999

spring:
  application:
    name: gateway
  profiles:
    active: dev
  config:
    import: 
      - "optional:nacos:gateway-routes.yml"
      - "optional:nacos:common-config.yml"
  cloud:
    nacos:
      config:
        server-addr: localhost:18848
        namespace: public
        group: DEFAULT_GROUP
        file-extension: yml
        refresh-enabled: true
        shared-configs:
          - data-id: common-config.yml
            group: DEFAULT_GROUP
            refresh: true
        extension-configs:
          - data-id: gateway-routes.yml
            group: DEFAULT_GROUP
            refresh: true
      discovery:
        server-addr: localhost:18848
        namespace: public
        group: DEFAULT_GROUP
  
  # 禁用静态资源的自动配置，避免与网关路由冲突
  web:
    resources:
      add-mappings: false

  # 禁用 properties migrator 警告
  main:
    banner-mode: console

# 暴露配置刷新端点
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info
    
# 日志配置
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG
    org.springframework.boot.context.properties: WARN