spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        # 路由到 server01 服务
        - id: server01_route
          uri: http://localhost:9801
          predicates:
            - Path=/server01/**
          filters:
            - StripPrefix=1
            - AddResponseHeader=X-Response-From, Gateway
        
        # 路由到 server02 服务
        - id: server02_route
          uri: http://localhost:9802
          predicates:
            - Path=/server02/**
          filters:
            - StripPrefix=1
            - AddResponseHeader=X-Response-From, Gateway
        
        # API路由 - 可以根据需要添加更多路由规则
        - id: api_route
          uri: http://localhost:9801
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
            - AddRequestHeader=X-Gateway-Request, true
      
      # 全局 CORS 配置
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowedorigins: "*"
                allowedmethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedheaders: "*"
                allowcredentials: false

  # 禁用 properties migrator 警告
  main:
    banner-mode: console
    
# 服务器配置
server:
  port: 9999
  
# 日志配置
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG
    org.springframework.boot.context.properties: WARN