services:
  demo-nacos:
    image: nacos/nacos-server:latest
    container_name: demo-nacos
    ports:
      - "18080:8080" # 主要端口，客户端连接
      - "18848:8848" # gRPC端口（2.0+版本需要）
      - "19849:9849" # gRPC端口（客户端gRPC请求）
    environment:
      - MODE=standalone
      - NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789
      - NACOS_AUTH_IDENTITY_KEY=demo-nacos
      - NACOS_AUTH_IDENTITY_VALUE=demo-nacos
    volumes:
      - ./data/nacos-data:/home/nacos/data
      - ./data/nacos-logs:/home/nacos/logs
    networks:
      - nacos-network
    restart: unless-stopped # 自动重启策略

networks:
  nacos-network:
    driver: bridge
