server:
  port: 9999

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        # 路由到 server01 服务
        - id: server01_route
          uri: lb://server01-service
          predicates:
            - Path=/server01/**
          filters:
            - StripPrefix=1
            - AddResponseHeader=X-Response-From, Gateway

        # 路由到 server02 服务
        - id: server02_route
          uri: lb://server02-service
          predicates:
            - Path=/server02/**
          filters:
            - StripPrefix=1
            - AddResponseHeader=X-Response-From, Gateway

        # API路由 - 路由到 server01
        - id: api_route
          uri: lb://server01-service
          predicates:
            - Path=/api/**
          filters:
            - AddRequestHeader=X-Gateway-Request, true

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    nacos:
      discovery:
        server-addr: localhost:18848

  # 禁用静态资源的自动配置，避免与网关路由冲突
  webflux:
    static-path-pattern: false

# 日志配置
logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.web.reactive: INFO
    com.alibaba.nacos: INFO