spring:
  cloud:
    gateway:
      routes:
        - id: example_route
          uri: lb://example-service
          predicates:
            - Path=/example/**
          filters:
            - StripPrefix=1