spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:18848
    gateway:
      server:
        webflux:
          routes:
            # 路由到 server01 服务
            - id: server01_route
              uri: lb://server01-service
              predicates:
                - Path=/server01/**
              filters:
                - StripPrefix=1
                - AddResponseHeader=X-Response-From, Gateway

            # 路由到 server02 服务
            - id: server02_route
              uri: lb://server02-service
              predicates:
                - Path=/server02/**
              filters:
                - StripPrefix=1
                - AddResponseHeader=X-Response-From, Gateway

            # API路由 - 可以根据需要添加更多路由规则
            - id: api_route
              uri: lb://api-service
              predicates:
                - Path=/api/**
              filters:
                - StripPrefix=1
                - AddRequestHeader=X-Gateway-Request, true
          discovery:
            locator:
              enabled: true
  
  # 禁用静态资源的自动配置，避免与网关路由冲突
  web:
    resources:
      add-mappings: false

  # 禁用 properties migrator 警告
  main:
    banner-mode: console
    
# 日志配置
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG
    org.springframework.boot.context.properties: WARN