


### 直接调用服务（绕过网关）-----------------------------------
### 服务01 - 直接调用
GET http://localhost:9801/api/hello

### 服务02 - 直接调用
GET http://localhost:9802/api/hello

### 通过网关调用服务 ----------------------------------------

### 网关 - 直接调用服务01
GET http://localhost:9999/server01/api/hello
### 网关 - 直接调用服务02
GET http://localhost:9999/server02/api/hello